### ISSUE TITLE
Не срабатывает отписка

### ISSUE THREAD

**Issue by Luger-git** [sazanof/MODxLetters#21]
Здравствуйте! Почему то не работает отписка( 
Ввожу в форму адрес, жму на «Отписаться» и ничего, никаких сообщений, никаких писем. Подписчик как был так и остался на месте. Помогите разобраться пожалуйста!

Вызов сниппета стандартный, без ajax.
Код формы стандартный, из файла.
Если что, вот эта форма на сайте: anzu.adjikatest2.ru/otpisatsya-ot-rassylki.html
Версия модуля последняя.
Версия modx: 1.4.9

**Comment by Luger-git** [comment]
Если будет нужен доступ к админке, скажите, пришлю.

**Comment by sazanof** [comment]
Прошу протестировать, тк у меня пока нет такой возможности

**Comment by Luger-git** [comment]
Простите, не очень понимаю, туплю возможно. Что протестировать?
Как не работала, так и не работает...

**Comment by sazanof** [comment]
Выше коммит (самый последний)
его посмотрите, перекачайте файлы или внесите изменения согласно коммиту

**Comment by sazanof** [comment]
https://github.com/sazanof/MODxLetters/commit/df7d88e2d1684e6de96d19ef60ba531b10335b5d

**Comment by Luger-git** [comment]
Хм... Появилось сообщение "На вашу почту отправлено письмо со ссылкой, перейдя по которой вы можете отписаться от новостной рассылки" Письмо пришло, по ссылке попадаю на страницу отписки, там опять надпись "На вашу почту отправлено письмо со ссылкой, перейдя по которой вы можете отписаться от новостной рассылки" Подписчик не удалился(

**Comment by Luger-git** [comment]
Простите! Я дурак, работает!!! Спасибо огромное!!!

**Comment by Luger-git** [comment]
Единственное что хотелось бы добавить надпись о удачной отписке, после перехода по ссылке. А то сейчас пустота. Это возможно?

**Comment by sazanof** [comment]
значение по умолчанию после отписки $lang['unsubscribe_success']
