### ISSUE TITLE
Редактирование подписчика Баг!

### ISSUE THREAD

**Issue by lector1982** [sazanof/MODxLetters#6]
При редактировании подписчика он не редактируется, а делается его копия с новыми изменениям

**Comment by sazanof** [comment]
https://github.com/sazanof/MODxLetters/commit/2016ca976f279755341ac810f5889fe8b54d6551

в этом коммите правил
версия какая, откуда качали?

**Comment by sazanof** [comment]
6c6b80cdc037c885d455e572993a965514897a1a
7355c5385c47cdf5251c7ba4331bcf94eaf6bfb7
4331a8c6ccb9295597744c3d9e3bb2cb5b564834
исправил
