### ISSUE TITLE
Не работает вызов двух сниппетов на одной странице

### ISSUE THREAD

**Issue by lector1982** [sazanof/MODxLetters#8]
У меня один раз сниппет вызывается на Главной странице, там идет подписка на Новинки, а второй раз в чанке футера, который подключается во всех шаблонах, и вот на остальных он работает, а на Главной нет почему-то

**Comment by sazanof** [comment]
посмотрю, Но это норма)

**Comment by lector1982** [comment]
Eform так могу работать) может им какие-то id давать надо как с Ditto когда-то был глюк, что если два  на одной странице, нужно было им id давать,пробовал им разные name дать формам самим, не помогло

**Comment by sazanof** [comment]
так есть параметр formName для разных имён формы. возможно reqiure вместо require_once нужен в сниппеое

**Comment by lector1982** [comment]
formname там с маленькой буквы, я пробовал давать разные. а в файле сниппета три инклуда, какой трогать?

**Comment by sazanof** [comment]
который в админке снтппет ЭВО

**Comment by sazanof** [comment]
возможно все, конечно, сейчас не могу проверить

**Comment by lector1982** [comment]
аааа, сейчас попробую

**Comment by lector1982** [comment]
помогло, спасибо!

**Comment by sazanof** [comment]
Так где именно-то?работу проверили?

**Comment by lector1982** [comment]
reqiure вместо require_once  в сниппете в админке, проверил, и то и то подписывает норм и везде показывается

**Comment by sazanof** [comment]
#8
